apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: test-cron-wf
spec:
  schedule: "* * * * *"
  suspend: false
  concurrencyPolicy: "Allow"
  startingDeadlineSeconds: 0
  successfulJobsHistoryLimit: 15
  workflowSpec:
    retryStrategy:
      limit: "1"
    entrypoint: whalesay
    templates:
      - name: whalesay
        failFast: true
        retryStrategy:
#          retryPolicy: Never
          backoff:
            maxDuration: 2m
        container:
          image: alpine:latest
          command: [ sh, -c ]
          args: [ "echo intentional failure; exit 1" ]