apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: test-cron-wf
spec:
  schedule: "* * * * *"
  suspend: false
  concurrencyPolicy: "Allow"
  startingDeadlineSeconds: 0
  successfulJobsHistoryLimit: 15
  workflowSpec:
    entrypoint: whalesay
    templates:
      - name: whalesay
        restartPolicy: Never
        container:
          image: docker/whalesayxxx
          command: [ cowsay ]
          args: [ "hello world" ]