apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: exit-workflow
spec:
  schedule: "* * * * *"
  suspend: true
  concurrencyPolicy: "Forbid"
  startingDeadlineSeconds: 0
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  workflowSpec:
    retryStrategy:
      limit: "1"
      retryPolicy: "Always"
    entrypoint: whalesay
    templates:
      - name: whalesay
        failFast: true
        retryStrategy:
          limit: "1"
          retryPolicy: "Always"
        container:
          image: alpineggg:latest
          command: [ sh, -c ]
          args: [ "echo intentional failure; exit 1" ]